#!/usr/bin/env python3
"""Build the static Aurora gallery manifest from media/gallery."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MEDIA_ROOT = ROOT / "media" / "gallery"
OUTPUT = ROOT / "data" / "gallery-data.js"

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".avif"}
VIDEO_EXTENSIONS = {".mp4", ".webm", ".ogv"}


def natural_key(path: Path) -> list[object]:
    import re
    return [int(chunk) if chunk.isdigit() else chunk.lower() for chunk in re.split(r"(\d+)", str(path))]


def clean_category(path: Path) -> str:
    name = path.parent.name if path.parent != MEDIA_ROOT else "Aurora"
    if "-" in name and name.split("-", 1)[0].isdigit():
        name = name.split("-", 1)[1]
    return name.replace("-", " ").replace("_", " ").title()


def clean_title(path: Path) -> str:
    title = path.stem.replace("-", " ").replace("_", " ").strip()
    return " ".join(part.capitalize() for part in title.split()) or "Aurora"


def main() -> None:
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
    entries = []
    for path in sorted(MEDIA_ROOT.rglob("*"), key=natural_key):
        if not path.is_file() or path.name.startswith(".") or path.name.lower() == "readme.md":
            continue
        suffix = path.suffix.lower()
        if suffix not in IMAGE_EXTENSIONS | VIDEO_EXTENSIONS:
            continue
        relative = path.relative_to(ROOT).as_posix()
        entries.append({
            "file": relative,
            "type": "video" if suffix in VIDEO_EXTENSIONS else "image",
            "category": clean_category(path),
            "title": clean_title(path),
            "alt": f"Aurora — {clean_title(path)}",
        })

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(entries, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// Generated by tools/build_gallery.py. Keep this file committed for GitHub Pages.\n"
        f"window.AURORA_MEDIA = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(entries)} media entries to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
